### PR TITLE
Don't eat shift / double clicks from ClickableItem

### LINKED ISSUE #168: Bug Shift click
Shift click doesn't working

### PR DESCRIPTION
**Pull request by 2008Choco**
Currently, shift clicking and double clicking are completely eaten by the InventoryManager's `InvListener`. This hinders some otherwise useful functionality. This PR removes the hiding of these actions (and thus, click types).

Closes #168

### CODE REVIEW

**Comment by portlek** [comment]
It's ok, but the library also needs bottom-inventory controller, because you can move items into the top inventory.

**Comment by 2008Choco** [comment]
Fair point. Let me adjust the snippet quickly.

**Comment by portlek** [comment]
Yeah It's enough for now. But for the future, someone can want to make, for example, a custom crafting table/furnace which you have to put your items to the top inventory. So the exact solution to that, customizable bottom inventory within the library.
My library has these methods, maybe someone implements these methods into the SmartInvs too.
image

File: src/main/java/fr/minuskube/inv/InventoryManager.java [hunk 1]
```diff
@@ -123,17 +124,21 @@ public void onInventoryClick(InventoryClickEvent e) {
...
-            if (e.getAction() == InventoryAction.COLLECT_TO_CURSOR || e.getAction() == InventoryAction.MOVE_TO_OTHER_INVENTORY) {
-                e.setCancelled(true);
-                return;
-            }
-
-            if (e.getAction() == InventoryAction.NOTHING && e.getClick() != ClickType.MIDDLE) {
-                e.setCancelled(true);
-                return;
+            // Restrict putting items from the bottom inventory into the top inventory
+            Inventory clickedInventory = e.getClickedInventory();
```
Comment (portlek) [inline src/main/java/fr/minuskube/inv/InventoryManager.java:128]: Maybe need a null-check to avoid inventory-outside clicking.

Comment (2008Choco) [reply src/main/java/fr/minuskube/inv/InventoryManager.java:128]: Referential equality is in and of itself a null check. Not necessary.

Comment (portlek) [reply src/main/java/fr/minuskube/inv/InventoryManager.java:128]: Yea I know, but maybe in the future someone use the clickedInventory without null-check. I don't know maybe I'm a little bit paranoid :D

Comment (2008Choco) [reply src/main/java/fr/minuskube/inv/InventoryManager.java:128]: I think that's a bridge to cross when somebody gets to it :)

**Review by portlek — APPROVED** [review]

**Review by MinusKube — APPROVED** [review]

**Comment by MinusKube** [comment]
Thanks :)
